/*try{
    a
}
catch(err){
    // console.log(err)
    console.log(err.name)
    console.log(err.message)
}
console.log("At end")*/

/*try{
    console.log("a")
}
catch(err){
    console.log("b")
}
finally{
    console.log("c")
}*/
try{
    a
}
catch(err){
    console.log("b")
}
finally{
    console.log("c")
}
