/*console.log("before try")
try{
console.log("1")
a
console.log("2")
}
catch(err){
console.log("Some error is there")
}
console.log("after catch")*/

/*console.log("before try")
try{
console.log("1")
a=10
console.log("2")
}
catch(err){
console.log("Some error is there")
}
console.log("after catch")*/
/*let a =10
let b =20

try{

console.log(a,b,c)

}
catch(err){
    console.log("Some error is there")
}
console.log("hello world")*/
